export const ADD_FAVORITE_TERM = 'ADD_FAVORITE_TERM';
export const REMOVE_FAVORITE_TERM = 'REMOVE_FAVORITE_TERM';
export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';

// Módulo Clientes
export const CLIENTE_OPEN_FORM = 'CLIENTE_OPEN_FORM';
export const ACCION_NUEVO_CLIENTE = 'ACCION_NUEVO_CLIENTE';
export const ACCION_LIMPIAR_CLIENTE = 'ACCION_LIMPIAR_CLIENTE';